Sage Evergreen Documentation
============================
Beth Longwell <blongwel@eou.edu>; Brent Mills <brent@hoodriverlibrary.org>
:toc:
:icons:
:numbered:

Introduction to Evergreen
-------------------------
	Give a quick introduction to the System, what we run on, who makes up Sage/Evergreen,etc...

Overview of modules
-------------------
	Circulation
	Cataloging
	OPAC/Catalog
	Server Admin
  
Getting Started
---------------
	Logging in to Evergreen
	Setting up a Workstation
		-Configuring Receipt Templates
		-Configuring Receipt Printers	
		
Circulation Module
------------------

Dealing with Patrons
~~~~~~~~~~~~~~~~~~~
	-Searching, Registering, Updating
	-Patron Alerts, Notes
	-Merging Patron Records
	-Deleting Patron Records

Dealing with Items
~~~~~~~~~~~~~~~~~
	-Check out, Check In, Renewing (editing due date)
	-Marking Item Lost, Claimed Returned/Never Checked Out
	
	-Going through the Item Status Screen
		-Checking multiple items, Loading text list
		-Editing items from Item Status (link to Cataloging)
		
Dealing with Holds
~~~~~~~~~~~~~~~~~
	-Placing, Managing, Capturing, Find Another Target
		-Holds Pull List, Holds Shelf List, Clear Shelf List

Dealing with Transits
~~~~~~~~~~~~~~~~~~~~
	-When does the Status Change? How to receive an In Transit Item?
	-Checking Transit List
	-Canceling Transits
				

Cataloging Module
-----------------

Searching the OPAC/Catalog
~~~~~~~~~~~~~~~~~~~~~~~~~
	-Advanced/Numeric Search
	-MARC Expert Search
	-Z39.50 Search/Comparison with Catalog
	
Adding Holdings to Existing Sage Records
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
		-Adding Items to title records
		-Targeting Holds with New Items
		-Adding holdings for non-physical/electronic resources
		
Editing/Maintaining Sage Holdings
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
	-Necessary Permission Level
	-Copy Editor/Edit Item Attributes/Item Status(link from Circ)
	-Using Item/Copy Templates
		-Saving locally, modifying 
		-Exporting/Importing
	-Batch Update Items
		-Item Status/Copy Buckets(link)
			-Deleting/Modifying
	-Transfer Holdings to a New Record
	-Deleting Holdings
		-Records
		-Volumes
		-Copy/Item Level
	-Replacing Barcodes
	-Adding Bibliographic Records to Sage
		-Necessary Permission Level
		-MARC imports via Z39.50
		-MARC Batch Import/Export
		-Sage’s Minimum MARC record
		-Creating New MARC records (original cataloging)
		-Cataloging Non-Physical Items (link)
	-Using The MARC Editor
		-Editing Overview
		-OPAC Icons/Facet Search Fields (999 fields)
		-Merging Bib Records in Evergreen
		-Deleting MARC Records
	-Copy Alerts
	-Copy Buckets
	-Record Buckets
	
OPAC
----
	-What is an OPAC/Overview?
	-Types of Searching
	-Using "My Account"
	-Mobile OPAC (for tablets, phones)

Administrative Section
----------------------
Reports
~~~~~~
	-Overview, Who can Run them
	-Folders
	-Using Templates, Creating Templates
	-Modifying a template/Report from Scratch

Inventory
~~~~~~~~
  -Our Procedure
	

Staff Accounts
~~~~~~~~~~~~~
  -Registering New Staff Accounts
  -Editing Staff Accounts
  -Working Locations
  -Granting Privileges

Self Check Module
~~~~~~~~~~~~~~~~
  -Staff Portion of Self Check
  -Basic Check Out, View Items Out, View Holds, View Fines
  -Print Receipt
  -Optional Firefox Add-ons

Offline Transactions Module
~~~~~~~~~~~~~~~~~~~~~~~~~~
  -When to use
  -Patron Registration
  -Check Out, Check In, Renew
  -Uploading Offline Transactions when connection is back

Editing/Adding Book Cover Jackets
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  -Logging in to OpenLibrary.org
  -Editing incorrect/missing book jacket in catalog
	
	
More.... 
^^^^^^^^
CAUTION: What Else to add?

// Command to Generate HTML: asciidoctor -a toc2 -a data-uri -a icons -a linkcss -a stylesheet=foundation-lime.css -a stylesdir=~/asciidoctor-stylesheet-factory/stylesheets sample.ascidoc //
